// Explicit Vercel function for the nested order-payment endpoint.
// This avoids relying on the root catch-all function for dynamic PATCH routes.
// @ts-ignore - dist/index.cjs is generated by the Vercel build command.
export { default } from "../../../artifacts/api-server/dist/index.cjs";
