// Explicit Vercel route for /api/admin/:resource.
// The generic catch-all also serves the API, but Vercel's filesystem routing
// is more reliable when the admin collection route is declared explicitly.
// @ts-ignore - dist/index.cjs is generated by the Vercel build command.
export { default } from "../../artifacts/api-server/dist/index.cjs";
