// Explicit Vercel route for /api/admin/:resource/:id.
// @ts-ignore - dist/index.cjs is generated by the Vercel build command.
export { default } from "../../../artifacts/api-server/dist/index.cjs";
