import { useEffect, useMemo, useState } from "react";
import { Link } from "wouter";
import { Plus, Search, Pencil, Trash2, ArrowLeft, ShieldCheck, Building2, Users, KeyRound, BriefcaseBusiness, Boxes, PackageCheck, ChevronLeft, ChevronRight, X, Save, Eye, EyeOff, CheckSquare, Square, Shield } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

type Resource = "users" | "branches" | "roles" | "permissions" | "services" | "packages" | "inventory";
type RecordData = Record<string, unknown> & { id?: number };
type Option = { id: number; name: string; username?: string; status?: string };
type Permission = { id: number; key: string; name: string; module: string; action: string; description?: string; granted?: boolean };
type Config = { title: string; description: string; icon: typeof Users; fields: string[]; labels: Record<string, string> };

const configs: Record<Resource, Config> = {
  users: { title: "Users", description: "Manage staff accounts, credentials, roles and branch assignments.", icon: Users, fields: ["name", "username", "role_id", "branch_id", "status", "address", "phone"], labels: { name: "Name", username: "Username", role_id: "Role", branch_id: "Assign Branch", status: "Status", address: "Address", phone: "Phone" } },
  branches: { title: "Branches", description: "Manage studio branches, contact details and branch managers.", icon: Building2, fields: ["name", "code", "address", "phone", "manager_user_id", "status"], labels: { name: "Branch Name", code: "Code", address: "Address", phone: "Phone", manager_user_id: "Manager", status: "Status" } },
  roles: { title: "Roles", description: "Define reusable staff roles and access levels.", icon: ShieldCheck, fields: ["name", "description", "status"], labels: { name: "Role Name", description: "Description", status: "Status" } },
  permissions: { title: "Permissions", description: "Define granular actions available to roles.", icon: KeyRound, fields: ["key", "name", "module", "action", "description"], labels: { key: "Permission Key", name: "Name", module: "Module", action: "Action", description: "Description" } },
  services: { title: "Services", description: "Configure normal and urgent service pricing, delivery rules and availability.", icon: BriefcaseBusiness, fields: ["name", "code", "price", "is_free", "urgent_allowed", "urgent_price", "normal_delivery_days", "urgent_delivery_days", "description", "status"], labels: { name: "Service Name", code: "Code", price: "Normal Price", is_free: "Free", urgent_allowed: "Urgent Allowed", urgent_price: "Urgent Price", normal_delivery_days: "Normal Delivery (days)", urgent_delivery_days: "Urgent Delivery (days)", description: "Description", status: "Status" }, },
  packages: { title: "Packages", description: "Manage service packages and their pricing.", icon: Boxes, fields: ["name", "code", "price", "description", "status"], labels: { name: "Package Name", code: "Code", price: "Price", description: "Description", status: "Status" } },
  inventory: { title: "Inventory Items", description: "Manage inventory master items and low-stock thresholds.", icon: PackageCheck, fields: ["name", "sku", "category", "unit", "quantity", "minimum_quantity", "status"], labels: { name: "Item Name", sku: "SKU", category: "Category", unit: "Unit", quantity: "Quantity", minimum_quantity: "Minimum Quantity", status: "Status" } },
};

function display(value: unknown) { return value === null || value === undefined || value === "" ? "—" : String(value); }
function isTrue(value: unknown) { return value === true || String(value ?? "").toLowerCase() === "true"; }
function isActive(value: unknown) { return String(value ?? "").trim().toUpperCase() === "ACTIVE"; }
function statusClass(value: unknown) { return isActive(value) ? "bg-emerald-500/10 text-emerald-700 dark:text-emerald-400" : "bg-muted text-muted-foreground"; }
function statusLabel(value: unknown) { return String(value ?? "").toUpperCase() === "INACTIVE" ? "Not Active" : String(value ?? "Active").toLowerCase() === "active" ? "Active" : display(value); }
function inputType(field: string) { return ["price", "urgent_price", "normal_delivery_days", "urgent_delivery_days", "quantity", "minimum_quantity", "role_id", "branch_id", "manager_user_id"].includes(field) ? "number" : "text"; }
async function readApiResponse(response: Response) { const text = await response.text(); if (!text) return null; const contentType = response.headers.get("content-type") ?? ""; if (contentType.includes("application/json")) { try { return JSON.parse(text) as unknown; } catch { return { error: "The server returned invalid JSON." }; } } return { error: text.replace(/<[^>]*>/g, "").trim() || `Request failed with status ${response.status}.` }; }
function apiError(data: unknown, fallback: string) { return data && typeof data === "object" && "error" in data && typeof (data as { error?: unknown }).error === "string" ? (data as { error: string }).error : fallback; }
function formSignature(form: Record<string, string>) { return JSON.stringify(Object.keys(form).sort().reduce<Record<string, string>>((acc, key) => { acc[key] = form[key] ?? ""; return acc; }, {})); }

function validateService(form: Record<string, string>) {
  const errors: Record<string, string> = {};
  const name = form.name?.trim() ?? ""; const code = form.code?.trim() ?? ""; const price = Number(form.price); const free = isTrue(form.is_free); const urgent = isTrue(form.urgent_allowed);
  const urgentPrice = form.urgent_price?.trim() === "" ? null : Number(form.urgent_price); const normalDays = Number(form.normal_delivery_days); const urgentDays = form.urgent_delivery_days?.trim() === "" ? null : Number(form.urgent_delivery_days);
  const description = form.description?.trim() ?? "";
  if (!name) errors.name = "Service name is required."; else if (!/^\S(?:.*\S)?$/u.test(name)) errors.name = "Service name cannot start or end with whitespace."; else if (name.length > 120) errors.name = "Service name cannot exceed 120 characters.";
  if (!code) errors.code = "Code is required."; else if (!/^[A-Za-z0-9_-]+$/.test(code)) errors.code = "Code may contain letters, numbers, hyphens and underscores only.";
  if (!Number.isFinite(price) || price < 0) errors.price = "Price must be a number greater than or equal to 0.";
  if (free && price !== 0) errors.price = "Free services must have a price of 0.";
  if (description.length > 500) errors.description = "Description cannot exceed 500 characters.";
  if (!form.status) errors.status = "Status is required.";
  if (!Number.isInteger(normalDays) || normalDays < 0) errors.normal_delivery_days = "Normal delivery days must be a whole number >= 0.";
  if (!urgent) { if (urgentPrice !== null) errors.urgent_price = "Clear Urgent Price when Urgent is not allowed."; if (urgentDays !== null) errors.urgent_delivery_days = "Clear Urgent Delivery when Urgent is not allowed."; }
  else { if (urgentPrice === null || !Number.isFinite(urgentPrice) || urgentPrice < 0) errors.urgent_price = "Urgent Price is required and must be >= 0."; if (urgentDays === null || !Number.isInteger(urgentDays) || urgentDays < 0) errors.urgent_delivery_days = "Urgent Delivery is required and must be a whole number >= 0."; else if (urgentDays > normalDays) errors.urgent_delivery_days = "Urgent delivery cannot be longer than normal delivery."; }
  return errors;
}

function validateGeneric(form: Record<string, string>, resource: Resource) {
  const errors: Record<string, string> = {}; const required = (f: string, msg: string) => { if (!form[f]?.trim()) errors[f] = msg; };
  if (resource === "users") { required("name", "Name is required."); required("username", "Username is required."); required("role_id", "Role is required."); required("branch_id", "Assign Branch is required."); required("status", "Status is required."); }
  else if (resource === "branches") { required("name", "Branch name is required."); required("code", "Branch code is required."); required("status", "Status is required."); if (form.code && !/^[A-Za-z0-9_-]+$/.test(form.code)) errors.code = "Code may contain letters, numbers, hyphens and underscores only."; }
  else if (resource === "roles") { required("name", "Role name is required."); required("status", "Status is required."); }
  else if (resource === "permissions") { for (const f of ["key", "name", "module", "action"]) required(f, `${f} is required.`); if (form.key && !/^[A-Za-z0-9._-]+$/.test(form.key)) errors.key = "Permission key may contain letters, numbers, dots, hyphens and underscores only."; }
  else if (resource === "packages") { required("name", "Package name is required."); required("code", "Code is required."); required("price", "Price is required."); required("status", "Status is required."); if (form.price && (!Number.isFinite(Number(form.price)) || Number(form.price) < 0)) errors.price = "Price must be >= 0."; }
  else if (resource === "inventory") { required("name", "Item name is required."); required("sku", "SKU is required."); required("unit", "Unit is required."); required("status", "Status is required."); }
  return errors;
}

export default function AdminManagement({ resource }: { resource: Resource }) {
  const config = configs[resource]; const Icon = config.icon;
  const [rows, setRows] = useState<RecordData[]>([]); const [search, setSearch] = useState(""); const [editing, setEditing] = useState<RecordData | null>(null); const [form, setForm] = useState<Record<string, string>>({}); const [initialForm, setInitialForm] = useState<Record<string, string>>({});
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [modalError, setModalError] = useState(""); const [page, setPage] = useState(1); const pageSize = 10; const [showPassword, setShowPassword] = useState(false);
  const [roles, setRoles] = useState<Option[]>([]); const [branches, setBranches] = useState<Option[]>([]); const [managers, setManagers] = useState<Option[]>([]);
  const [permissionModal, setPermissionModal] = useState<RecordData | null>(null); const [allPermissions, setAllPermissions] = useState<Permission[]>([]); const [selectedPermissions, setSelectedPermissions] = useState<number[]>([]); const [permissionSearch, setPermissionSearch] = useState(""); const [permissionsSaving, setPermissionsSaving] = useState(false);

  const load = async (query = search) => { setLoading(true); setError(""); try { const response = await fetch(`/api/admin/${resource}${query ? `?search=${encodeURIComponent(query)}` : ""}`, { headers: { Accept: "application/json" } }); const data = await readApiResponse(response); if (!response.ok) throw new Error(apiError(data, `Failed to load ${config.title.toLowerCase()}.`)); setRows(Array.isArray(data) ? data as RecordData[] : []); setPage(1); } catch (e) { setError(e instanceof Error ? e.message : "Failed to load admin data"); } finally { setLoading(false); } };
  useEffect(() => { void load(""); }, [resource]);
  const loadOptions = async () => { try { const [rr, br, ur] = await Promise.all([fetch("/api/admin/roles"), fetch("/api/admin/branches"), fetch("/api/admin/options/users")]); const rd = await readApiResponse(rr); const bd = await readApiResponse(br); const ud = await readApiResponse(ur); setRoles(Array.isArray(rd) ? rd.filter((x): x is Option => typeof x === "object" && x !== null && typeof (x as Option).id === "number" && isActive((x as Option).status)) : []); setBranches(Array.isArray(bd) ? bd.filter((x): x is Option => typeof x === "object" && x !== null && typeof (x as Option).id === "number" && isActive((x as Option).status)) : []); setManagers(Array.isArray(ud) ? ud as Option[] : []); } catch { setRoles([]); setBranches([]); setManagers([]); } };
  const openCreate = () => { const next: Record<string, string> = { status: "ACTIVE", is_free: "false", urgent_allowed: "false", normal_delivery_days: "0" }; setEditing({}); setForm(next); setInitialForm(next); setModalError(""); setShowPassword(false); if (resource === "users" || resource === "branches") void loadOptions(); };
  const openEdit = (row: RecordData) => { const next: Record<string, string> = Object.fromEntries(config.fields.map((f) => [f, row[f] === null || row[f] === undefined ? "" : String(row[f])])); setEditing(row); setForm(next); setInitialForm(next); setModalError(""); setShowPassword(false); if (resource === "users" || resource === "branches") void loadOptions(); };

  const openPermissions = async (role: RecordData) => { if (!role.id) return; try { const response = await fetch(`/api/admin/roles/${role.id}/permissions`); const data = await readApiResponse(response); if (!response.ok || !Array.isArray(data)) throw new Error(apiError(data, "Failed to load permissions.")); const list = data as Permission[]; setAllPermissions(list); setSelectedPermissions(list.filter((p) => p.granted).map((p) => p.id)); setPermissionSearch(""); setPermissionModal(role); } catch (e) { setError(e instanceof Error ? e.message : "Failed to load permissions."); } };
  const savePermissions = async () => { if (!permissionModal?.id) return; setPermissionsSaving(true); try { const response = await fetch(`/api/admin/roles/${permissionModal.id}/permissions`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ permission_ids: selectedPermissions }) }); const data = await readApiResponse(response); if (!response.ok) throw new Error(apiError(data, "Failed to save permissions.")); setPermissionModal(null); } catch (e) { setError(e instanceof Error ? e.message : "Failed to save permissions."); } finally { setPermissionsSaving(false); } };

  const validationErrors = editing ? resource === "services" ? validateService(form) : validateGeneric(form, resource) : {}; const dirty = editing ? formSignature(form) !== formSignature(initialForm) : false; const canSave = !!editing && dirty && !saving && Object.keys(validationErrors).length === 0;
  const save = async () => { if (!editing || !canSave) return; setSaving(true); setModalError(""); try {
    const body: Record<string, unknown> = {};
    if (resource === "services") { const free = isTrue(form.is_free); const urgent = isTrue(form.urgent_allowed); for (const field of config.fields) if (form[field] !== undefined) { if (["is_free", "urgent_allowed"].includes(field)) body[field] = isTrue(form[field]); else if (["price", "urgent_price", "normal_delivery_days", "urgent_delivery_days"].includes(field)) body[field] = form[field] === "" ? null : Number(form[field]); else body[field] = form[field]; } if (free) body.price = 0; if (!urgent) { body.urgent_price = null; body.urgent_delivery_days = null; } }
    else if (resource === "users") { for (const field of config.fields) if (form[field] !== undefined) body[field] = ["role_id", "branch_id"].includes(field) ? Number(form[field]) : field === "status" ? form[field].toUpperCase() : form[field]; if (form.password) body.password = form.password; }
    else if (resource === "branches") { for (const field of config.fields) if (form[field] !== undefined) body[field] = field === "manager_user_id" ? (form[field] ? Number(form[field]) : null) : field === "status" ? form[field].toUpperCase() : form[field]; }
    else { for (const field of config.fields) if (form[field] !== undefined) body[field] = inputType(field) === "number" ? (form[field] === "" ? null : Number(form[field])) : form[field]; }
    const response = await fetch(editing.id ? `/api/admin/${resource}/${editing.id}` : `/api/admin/${resource}`, { method: editing.id ? "PATCH" : "POST", headers: { "Content-Type": "application/json", Accept: "application/json" }, body: JSON.stringify(body) }); const data = await readApiResponse(response); if (!response.ok) throw new Error(apiError(data, "Save failed.")); setEditing(null); await load();
  } catch (e) { setModalError(e instanceof Error ? e.message : "Save failed."); } finally { setSaving(false); } };
  const remove = async (id: number) => { if (!window.confirm("Delete this record? This action cannot be undone.")) return; try { const response = await fetch(`/api/admin/${resource}/${id}`, { method: "DELETE" }); const data = await readApiResponse(response); if (!response.ok) throw new Error(apiError(data, "Delete failed.")); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Delete failed."); } };

  const columns = useMemo(() => resource === "users" ? ["name", "username", "role_name", "branch_name", "status"] : resource === "branches" ? ["name", "code", "manager_name", "phone", "status"] : resource === "services" ? ["name", "code", "price", "urgent_price", "status"] : config.fields.slice(0, resource === "permissions" ? 5 : 6), [config.fields, resource]);
  const totalPages = Math.max(1, Math.ceil(rows.length / pageSize)); const visibleRows = rows.slice((page - 1) * pageSize, page * pageSize);
  const fieldLabel = (field: string) => config.labels[field] ?? field;
  const renderSelect = (label: string, value: string, options: Option[], onChange: (v: string) => void, required = true) => <div className="space-y-1.5"><Label>{label} {required && <span className="text-destructive">*</span>}</Label><select value={value} onChange={(e) => onChange(e.target.value)} className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"><option value="">Choose</option>{options.map((o) => <option key={o.id} value={o.id}>{o.name}{o.username ? ` (${o.username})` : ""}</option>)}</select>{validationErrors[label === "Role" ? "role_id" : label === "Assign Branch" ? "branch_id" : "manager_user_id"] && <p className="text-xs text-destructive">{validationErrors[label === "Role" ? "role_id" : label === "Assign Branch" ? "branch_id" : "manager_user_id"]}</p>}</div>;
  const modules = Array.from(new Set(allPermissions.map((p) => p.module))).sort(); const filteredPermissions = allPermissions.filter((p) => !permissionSearch || `${p.key} ${p.name} ${p.module}`.toLowerCase().includes(permissionSearch.toLowerCase()));

  return <div className="p-4 sm:p-6 lg:p-8 max-w-[1500px] mx-auto w-full space-y-5">
    <div className="flex flex-col lg:flex-row lg:items-start justify-between gap-4"><div className="flex items-start gap-3"><Link href="/admin"><Button variant="outline" size="icon"><ArrowLeft className="w-4 h-4" /></Button></Link><div><div className="flex items-center gap-2"><div className="h-9 w-9 rounded-lg bg-primary/10 flex items-center justify-center"><Icon className="w-5 h-5 text-primary" /></div><h2 className="text-xl sm:text-2xl font-bold">{config.title}</h2></div><p className="text-sm text-muted-foreground mt-2">{config.description}</p></div></div><Button onClick={openCreate} className="gap-2"><Plus className="w-4 h-4" />Add {config.title.replace(/s$/, "")}</Button></div>
    <Card><CardContent className="p-3 sm:p-4"><div className="flex gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 w-4 h-4 text-muted-foreground" /><Input value={search} onChange={(e) => setSearch(e.target.value)} onKeyDown={(e) => e.key === "Enter" && void load()} placeholder={`Search ${config.title.toLowerCase()}...`} className="pl-9 h-9" /></div><Button onClick={() => void load()} variant="outline" className="h-9">Search</Button></div></CardContent></Card>
    {error && <div className="rounded-lg border border-destructive/30 bg-destructive/5 text-destructive px-4 py-3 text-sm">{error}</div>}
    <Card><CardHeader className="py-4 border-b"><CardTitle className="text-sm">{config.title} <span className="text-xs text-muted-foreground font-normal">({rows.length})</span></CardTitle></CardHeader><CardContent className="p-0 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b bg-muted/30">{columns.map((c) => <th key={c} className="text-left px-4 py-3 text-muted-foreground whitespace-nowrap">{c === "role_name" ? "Role" : c === "branch_name" ? "Branch" : c === "manager_name" ? "Manager" : fieldLabel(c)}</th>)}<th className="px-4 py-3 text-right text-muted-foreground">Actions</th></tr></thead><tbody>{loading ? <tr><td colSpan={columns.length + 1} className="p-10 text-center text-muted-foreground">Loading…</td></tr> : visibleRows.length === 0 ? <tr><td colSpan={columns.length + 1} className="p-10 text-center text-muted-foreground">No records found.</td></tr> : visibleRows.map((row) => <tr key={row.id} className="border-b last:border-0 hover:bg-muted/20">{columns.map((c) => <td key={c} className="px-4 py-3 whitespace-nowrap">{c === "status" ? <span className={`inline-flex rounded-full px-2 py-0.5 text-xs font-medium ${statusClass(row[c])}`}>{statusLabel(row[c])}</span> : c === "is_free" || c === "urgent_allowed" ? (isTrue(row[c]) ? "Yes" : "No") : display(row[c])}</td>)}<td className="px-4 py-3"><div className="flex justify-end gap-1">{resource === "roles" && <Button variant="ghost" size="icon" onClick={() => void openPermissions(row)} title="Manage permissions"><Shield className="w-4 h-4 text-primary" /></Button>}<Button variant="ghost" size="icon" onClick={() => openEdit(row)}><Pencil className="w-4 h-4" /></Button><Button variant="ghost" size="icon" onClick={() => void remove(Number(row.id))}><Trash2 className="w-4 h-4 text-destructive" /></Button></div></td></tr>)}</tbody></table></CardContent><div className="flex justify-between items-center px-4 py-3 border-t text-xs text-muted-foreground"><span>Page {page} of {totalPages}</span><div className="flex gap-1"><Button variant="outline" size="icon" className="h-8 w-8" disabled={page <= 1} onClick={() => setPage((p) => p - 1)}><ChevronLeft className="w-4 h-4" /></Button><Button variant="outline" size="icon" className="h-8 w-8" disabled={page >= totalPages} onClick={() => setPage((p) => p + 1)}><ChevronRight className="w-4 h-4" /></Button></div></div></Card>

    {editing && <div className="fixed inset-0 z-[100] bg-black/50 backdrop-blur-sm flex items-center justify-center p-4"><Card className="w-full max-w-3xl max-h-[92vh] overflow-y-auto"><CardHeader className="sticky top-0 z-20 bg-card border-b flex flex-row items-center justify-between"><div><CardTitle>{editing.id ? "Edit" : "Add"} {config.title.replace(/s$/, "")}</CardTitle><p className="text-xs text-muted-foreground mt-1">{resource === "services" ? "Configure the final normal/urgent price and delivery rules for this service." : "Keep the master data consistent across the studio."}</p></div><Button variant="ghost" size="icon" onClick={() => setEditing(null)}><X className="w-4 h-4" /></Button></CardHeader><CardContent className="p-5 space-y-5">
      {(Object.values(validationErrors).length || modalError) ? <div className="rounded-lg border border-destructive/30 bg-destructive/5 text-destructive px-4 py-3 space-y-1 text-sm">{modalError && <p>{modalError}</p>}{Object.values(validationErrors).map((m, i) => <p key={i}>• {m}</p>)}</div> : null}
      {resource === "services" ? <>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><div className="space-y-1.5"><Label>Service Name *</Label><Input value={form.name ?? ""} maxLength={120} onChange={(e) => setForm((p) => ({ ...p, name: e.target.value }))} />{validationErrors.name && <p className="text-xs text-destructive">{validationErrors.name}</p>}</div><div className="space-y-1.5"><Label>Code *</Label><Input value={form.code ?? ""} onChange={(e) => setForm((p) => ({ ...p, code: e.target.value.toUpperCase() }))} />{validationErrors.code && <p className="text-xs text-destructive">{validationErrors.code}</p>}</div></div>
        <div className="rounded-xl border p-4 space-y-4"><div className="font-semibold text-sm">Normal Pricing</div><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><div className="flex items-center gap-3 rounded-lg border p-3"><input type="checkbox" checked={isTrue(form.is_free)} onChange={(e) => setForm((p) => ({ ...p, is_free: String(e.target.checked), price: e.target.checked ? "0" : p.price }))} /><div><div className="text-sm font-medium">Free service</div><div className="text-xs text-muted-foreground">Free services always have a price of 0.</div></div></div><div className="space-y-1.5"><Label>Normal Price *</Label><Input type="number" min="0" step="0.01" disabled={isTrue(form.is_free)} value={form.price ?? ""} onChange={(e) => setForm((p) => ({ ...p, price: e.target.value }))} />{validationErrors.price && <p className="text-xs text-destructive">{validationErrors.price}</p>}</div></div></div>
        <div className="rounded-xl border p-4 space-y-4"><div className="font-semibold text-sm">Delivery</div><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><div className="space-y-1.5"><Label>Normal Delivery (days) *</Label><Input type="number" min="0" step="1" value={form.normal_delivery_days ?? "0"} onChange={(e) => setForm((p) => ({ ...p, normal_delivery_days: e.target.value }))} />{validationErrors.normal_delivery_days && <p className="text-xs text-destructive">{validationErrors.normal_delivery_days}</p>}</div><div className="flex items-center gap-3 rounded-lg border p-3"><input type="checkbox" checked={isTrue(form.urgent_allowed)} onChange={(e) => setForm((p) => ({ ...p, urgent_allowed: String(e.target.checked), urgent_price: e.target.checked ? p.urgent_price : "", urgent_delivery_days: e.target.checked ? p.urgent_delivery_days : "" }))} /><div><div className="text-sm font-medium">Urgent Allowed</div><div className="text-xs text-muted-foreground">Urgent is an alternative final price/state, not an extra fee.</div></div></div></div>{isTrue(form.urgent_allowed) && <div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><div className="space-y-1.5"><Label>Urgent Price *</Label><Input type="number" min="0" step="0.01" value={form.urgent_price ?? ""} onChange={(e) => setForm((p) => ({ ...p, urgent_price: e.target.value }))} />{validationErrors.urgent_price && <p className="text-xs text-destructive">{validationErrors.urgent_price}</p>}</div><div className="space-y-1.5"><Label>Urgent Delivery (days) *</Label><Input type="number" min="0" step="1" value={form.urgent_delivery_days ?? ""} onChange={(e) => setForm((p) => ({ ...p, urgent_delivery_days: e.target.value }))} />{validationErrors.urgent_delivery_days && <p className="text-xs text-destructive">{validationErrors.urgent_delivery_days}</p>}</div></div>}</div>
        <div className="space-y-1.5"><Label>Description</Label><textarea value={form.description ?? ""} onChange={(e) => setForm((p) => ({ ...p, description: e.target.value }))} maxLength={500} rows={3} className="flex w-full rounded-md border border-input bg-background px-3 py-2 text-sm" />{validationErrors.description && <p className="text-xs text-destructive">{validationErrors.description}</p>}</div>
        <div className="space-y-1.5"><Label>Status *</Label><select value={form.status ?? ""} onChange={(e) => setForm((p) => ({ ...p, status: e.target.value }))} className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"><option value="">Choose status</option><option value="ACTIVE">Active</option><option value="INACTIVE">Not Active</option></select>{validationErrors.status && <p className="text-xs text-destructive">{validationErrors.status}</p>}</div>
      </> : resource === "users" ? <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">{config.fields.map((f) => <div key={f} className="space-y-1.5"><Label>{config.labels[f]}</Label><Input type={f === "password" ? (showPassword ? "text" : "password") : inputType(f)} value={form[f] ?? ""} onChange={(e) => setForm((p) => ({ ...p, [f]: e.target.value }))} />{validationErrors[f] && <p className="text-xs text-destructive">{validationErrors[f]}</p>}</div>)}<div className="sm:col-span-2 space-y-1.5"><Label>Password {editing.id ? "(leave blank to keep current)" : "*"}</Label><div className="flex gap-2"><Input type={showPassword ? "text" : "password"} value={form.password ?? ""} onChange={(e) => setForm((p) => ({ ...p, password: e.target.value }))} /><Button type="button" variant="outline" size="icon" onClick={() => setShowPassword((v) => !v)}>{showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}</Button></div></div></div> : resource === "branches" ? <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">{config.fields.map((f) => f === "manager_user_id" ? renderSelect("Manager", form[f] ?? "", managers, (v) => setForm((p) => ({ ...p, [f]: v })), false) : <div key={f} className="space-y-1.5"><Label>{config.labels[f]}</Label><Input type={inputType(f)} value={form[f] ?? ""} onChange={(e) => setForm((p) => ({ ...p, [f]: e.target.value }))} />{validationErrors[f] && <p className="text-xs text-destructive">{validationErrors[f]}</p>}</div>)}</div> : resource === "roles" || resource === "permissions" ? <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">{config.fields.map((f) => <div key={f} className="space-y-1.5"><Label>{config.labels[f]}</Label><Input value={form[f] ?? ""} onChange={(e) => setForm((p) => ({ ...p, [f]: e.target.value }))} />{validationErrors[f] && <p className="text-xs text-destructive">{validationErrors[f]}</p>}</div>)}</div> : <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">{config.fields.map((f) => <div key={f} className="space-y-1.5"><Label>{config.labels[f]}</Label><Input type={inputType(f)} value={form[f] ?? ""} onChange={(e) => setForm((p) => ({ ...p, [f]: e.target.value }))} />{validationErrors[f] && <p className="text-xs text-destructive">{validationErrors[f]}</p>}</div>)}</div>}
      <div className="flex justify-between items-center gap-3 pt-4 border-t"><span className="text-xs text-muted-foreground">{dirty ? "Unsaved changes" : "No changes to save"}</span><div className="flex gap-2"><Button variant="outline" onClick={() => setEditing(null)}>Cancel</Button><Button onClick={() => void save()} disabled={!canSave} className="gap-2"><Save className="w-4 h-4" />{saving ? "Saving…" : "Save"}</Button></div></div>
    </CardContent></Card></div>}

    {permissionModal && <div className="fixed inset-0 z-[110] bg-black/60 flex items-center justify-center p-4"><Card className="w-full max-w-4xl max-h-[92vh] overflow-y-auto"><CardHeader className="flex flex-row items-center justify-between"><CardTitle className="flex items-center gap-2"><Shield className="w-5 h-5" />Permissions for {String(permissionModal.name)}</CardTitle><Button variant="ghost" size="icon" onClick={() => setPermissionModal(null)}><X className="w-4 h-4" /></Button></CardHeader><CardContent className="space-y-4"><Input value={permissionSearch} onChange={(e) => setPermissionSearch(e.target.value)} placeholder="Search permissions..." />{modules.map((module) => { const items = filteredPermissions.filter((p) => p.module === module); const ids = items.map((p) => p.id); const selected = ids.length > 0 && ids.every((id) => selectedPermissions.includes(id)); return <div key={module} className="rounded-xl border overflow-hidden"><div className="flex justify-between items-center bg-muted/30 px-4 py-3"><span className="font-semibold text-sm">{module}</span><Button variant="ghost" size="sm" onClick={() => setSelectedPermissions((cur) => selected ? cur.filter((id) => !ids.includes(id)) : Array.from(new Set([...cur, ...ids])))}>{selected ? "Clear module" : "Select module"}</Button></div><div className="grid md:grid-cols-2">{items.map((p) => { const checked = selectedPermissions.includes(p.id); return <button key={p.id} type="button" onClick={() => setSelectedPermissions((cur) => checked ? cur.filter((id) => id !== p.id) : [...cur, p.id])} className="flex items-start gap-2 text-left p-3 hover:bg-muted/30">{checked ? <CheckSquare className="w-4 h-4 text-primary mt-0.5" /> : <Square className="w-4 h-4 text-muted-foreground mt-0.5" />}<span><span className="block text-sm font-medium">{p.name}</span><span className="block text-xs text-muted-foreground font-mono">{p.key}</span></span></button>; })}</div></div>})}<div className="flex justify-end gap-2 border-t pt-4"><Button variant="outline" onClick={() => setPermissionModal(null)}>Cancel</Button><Button onClick={() => void savePermissions()} disabled={permissionsSaving}>{permissionsSaving ? "Saving…" : "Save permissions"}</Button></div></CardContent></Card></div>}
  </div>;
}
