import { useEffect, useMemo, useState } from "react";
import { Link } from "wouter";
import { ArrowLeft, Boxes, ChevronDown, Plus, Search, SlidersHorizontal, Trash2, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

type Status = "ALL" | "IN_STOCK" | "LOW_STOCK" | "OUT_OF_STOCK";
type Item = { id?: number; name: string; category: string; unit: string; quantity: number | string; minimum_quantity: number | string; unit_price: number | string; value: number | string; status: Exclude<Status, "ALL"> };
type Analytics = { total_items: number | string; low_stock_items: number | string; out_of_stock_items: number | string; in_stock_items: number | string };
async function read(response: Response) { const text = await response.text(); if (!text) return null; try { return JSON.parse(text) as unknown; } catch { return { error: text.replace(/<[^>]*>/g, "").trim() }; } }
function errorMessage(data: unknown, fallback: string) { return data && typeof data === "object" && typeof (data as { error?: unknown }).error === "string" ? (data as { error: string }).error : fallback; }
function num(value: unknown) { const n = Number(value); return Number.isFinite(n) ? n : 0; }
function displayNumber(value: unknown) { const n = num(value); return Number.isInteger(n) ? String(n) : String(n).replace(/\.0+$/, ""); }
function money(value: unknown) { return `${displayNumber(value)} EGP`; }
function statusLabel(status: Item["status"]) { return status === "OUT_OF_STOCK" ? "Out of Stock" : status === "LOW_STOCK" ? "Low" : "In Stock"; }
const emptyForm = { name: "", category: "", unit: "Pcs", quantity: "", minimum_quantity: "", unit_price: "" };

export default function InventoryManagement() {
  const [rows, setRows] = useState<Item[]>([]); const [analytics, setAnalytics] = useState<Analytics>({ total_items: 0, low_stock_items: 0, out_of_stock_items: 0, in_stock_items: 0 });
  const [categories, setCategories] = useState<string[]>([]); const [search, setSearch] = useState(""); const [category, setCategory] = useState("ALL"); const [status, setStatus] = useState<Status>("ALL"); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [formOpen, setFormOpen] = useState(false); const [editing, setEditing] = useState<Item | null>(null); const [adjusting, setAdjusting] = useState<Item | null>(null); const [adjustment, setAdjustment] = useState(""); const [saving, setSaving] = useState(false); const [form, setForm] = useState(emptyForm);

  const load = async () => { setLoading(true); setError(""); try {
    const params = new URLSearchParams(); if (search.trim()) params.set("search", search.trim()); if (category !== "ALL") params.set("category", category); if (status !== "ALL") params.set("status", status);
    const [itemsResponse, analyticsResponse, categoriesResponse] = await Promise.all([fetch(`/api/admin/inventory${params.toString() ? `?${params}` : ""}`), fetch("/api/admin/inventory/analytics"), fetch("/api/admin/inventory/categories")]);
    const items = await read(itemsResponse); const stats = await read(analyticsResponse); const categoryData = await read(categoriesResponse);
    if (!itemsResponse.ok) throw new Error(errorMessage(items, "Failed to load inventory.")); if (!analyticsResponse.ok) throw new Error(errorMessage(stats, "Failed to load inventory analytics."));
    setRows(Array.isArray(items) ? items as Item[] : []); if (stats && typeof stats === "object") setAnalytics(stats as Analytics); if (Array.isArray(categoryData)) setCategories(categoryData.map(String));
  } catch (e) { setError(e instanceof Error ? e.message : "Failed to load inventory."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [category, status]);

  const openCreate = () => { setEditing(null); setForm(emptyForm); setFormOpen(true); setError(""); };
  const openEdit = (item: Item) => { setEditing(item); setForm({ name: String(item.name ?? ""), category: String(item.category ?? ""), unit: String(item.unit ?? "Pcs"), quantity: String(item.quantity ?? ""), minimum_quantity: String(item.minimum_quantity ?? ""), unit_price: String(item.unit_price ?? "") }); setFormOpen(true); setError(""); };
  const closeForm = () => { setFormOpen(false); setEditing(null); setForm(emptyForm); };
  const validation = useMemo(() => { const next: Record<string, string> = {}; const name = form.name.trim(); const categoryName = form.category.trim(); const unit = form.unit.trim(); const quantity = Number(form.quantity); const minimum = Number(form.minimum_quantity); const price = Number(form.unit_price); if (!name) next.name = "Item Name is required."; else if (name.length > 120) next.name = "Item Name cannot exceed 120 characters."; if (!categoryName) next.category = "Category is required."; if (!unit) next.unit = "Unit is required."; if (form.quantity === "" || !Number.isInteger(quantity) || quantity < 0) next.quantity = "In Stock must be a non-negative whole number."; if (form.minimum_quantity === "" || !Number.isInteger(minimum) || minimum < 0) next.minimum_quantity = "Minimum Quantity must be a non-negative whole number."; if (form.unit_price === "" || !Number.isFinite(price) || price < 0) next.unit_price = "Unit Price must be >= 0."; return next; }, [form]);
  const save = async () => { if (Object.keys(validation).length || saving) return; setSaving(true); setError(""); try { const body = { name: form.name.trim(), category: form.category.trim(), unit: form.unit.trim(), quantity: Number(form.quantity), minimum_quantity: Number(form.minimum_quantity), unit_price: Number(form.unit_price) }; const response = await fetch(editing?.id ? `/api/admin/inventory/${editing.id}` : "/api/admin/inventory", { method: editing?.id ? "PATCH" : "POST", headers: { "Content-Type": "application/json", Accept: "application/json" }, body: JSON.stringify(body) }); const data = await read(response); if (!response.ok) throw new Error(errorMessage(data, "Save failed.")); closeForm(); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Save failed."); } finally { setSaving(false); } };
  const remove = async (id: number) => { if (!window.confirm("Delete this inventory item? This action cannot be undone.")) return; try { const response = await fetch(`/api/admin/inventory/${id}`, { method: "DELETE" }); const data = await read(response); if (!response.ok) throw new Error(errorMessage(data, "Delete failed.")); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Delete failed."); } };
  const adjust = async () => { const value = Number(adjustment); if (!adjusting?.id || !Number.isInteger(value) || value === 0) return; setSaving(true); setError(""); try { const response = await fetch(`/api/admin/inventory/${adjusting.id}/adjust`, { method: "POST", headers: { "Content-Type": "application/json", Accept: "application/json" }, body: JSON.stringify({ adjustment: value }) }); const data = await read(response); if (!response.ok) throw new Error(errorMessage(data, "Adjustment failed.")); setAdjusting(null); setAdjustment(""); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Adjustment failed."); } finally { setSaving(false); } };

  const tabs: Array<[Status, string, number | string]> = [["ALL", "All", analytics.total_items], ["LOW_STOCK", "Low Stock", analytics.low_stock_items], ["OUT_OF_STOCK", "Out of Stock", analytics.out_of_stock_items], ["IN_STOCK", "In Stock", analytics.in_stock_items]];
  return <div className="p-4 sm:p-6 lg:p-8 max-w-[1500px] mx-auto w-full space-y-5">
    <div className="flex items-center gap-2"><Link href="/admin"><Button variant="outline" size="icon" className="rounded-xl"><ArrowLeft className="w-4 h-4" /></Button></Link><div className="h-9 w-9 rounded-xl bg-primary/10 flex items-center justify-center"><Boxes className="w-5 h-5 text-primary" /></div><div><h2 className="text-xl font-bold">Inventory</h2><p className="text-xs text-muted-foreground">Track stock, pricing and availability.</p></div></div>
    <div className="flex flex-col lg:flex-row gap-3 items-stretch lg:items-center"><div className="relative flex-1"><Search className="absolute left-4 top-3.5 w-4 h-4 text-muted-foreground" /><Input value={search} onChange={(e) => setSearch(e.target.value)} onKeyDown={(e) => e.key === "Enter" && void load()} placeholder="Search inventory..." className="pl-11 h-12 rounded-xl border-muted-foreground/20 bg-background shadow-sm" /></div><div className="relative"><select value={category} onChange={(e) => setCategory(e.target.value)} className="h-12 min-w-[170px] appearance-none rounded-xl border border-muted-foreground/20 bg-background px-4 pr-10 text-sm shadow-sm outline-none focus:ring-2 focus:ring-primary/20"><option value="ALL">All Categories</option>{categories.map((c) => <option key={c} value={c}>{c}</option>)}</select><ChevronDown className="pointer-events-none absolute right-3 top-4 w-4 h-4 text-muted-foreground" /></div><Button onClick={openCreate} className="h-12 rounded-xl px-6 gap-2 bg-orange-500 hover:bg-orange-600"><Plus className="w-4 h-4" />Add Item</Button></div>
    <Card className="rounded-xl shadow-sm"><CardContent className="p-1.5"><div className="flex flex-wrap gap-1">{tabs.map(([key, label, count]) => <button key={key} onClick={() => setStatus(key)} className={`rounded-lg px-4 py-2.5 text-sm font-medium transition-colors ${status === key ? "bg-orange-500 text-white shadow-sm" : "text-slate-600 hover:bg-muted"}`}>{label}<span className={`ml-2 rounded-full px-2 py-0.5 text-xs ${status === key ? "bg-white/20 text-white" : "bg-muted text-muted-foreground"}`}>{displayNumber(count)}</span></button>)}</div></CardContent></Card>
    {error && <div className="rounded-xl border border-destructive/30 bg-destructive/5 text-destructive px-4 py-3 text-sm">{error}</div>}
    <Card className="overflow-hidden rounded-2xl border-muted-foreground/10 shadow-sm"><CardContent className="p-0 overflow-x-auto"><table className="w-full min-w-[980px] text-sm"><thead><tr className="border-b bg-slate-50/80">{["ITEM", "CATEGORY", "IN STOCK", "MIN", "UNIT PRICE", "VALUE", "STATUS", "ACTIONS"].map((h) => <th key={h} className={`px-5 py-4 text-[12px] font-medium tracking-wide text-slate-500 ${h === "ACTIONS" ? "text-right" : h === "IN STOCK" || h === "MIN" ? "text-center" : "text-left"}`}>{h}</th>)}</tr></thead><tbody>{loading ? <tr><td colSpan={8} className="p-12 text-center text-muted-foreground">Loading inventory…</td></tr> : rows.length === 0 ? <tr><td colSpan={8} className="p-12 text-center text-muted-foreground">No inventory items found.</td></tr> : rows.map((row) => <tr key={row.id} className="border-b last:border-0 hover:bg-slate-50/60 transition-colors"><td className="px-5 py-4"><div className="flex items-center gap-3"><div className="h-10 w-10 shrink-0 rounded-xl bg-slate-100 flex items-center justify-center"><Boxes className="w-5 h-5 text-slate-500" /></div><div className="font-semibold text-slate-800">{row.name}</div></div></td><td className="px-5 py-4 text-slate-500">{row.category}</td><td className="px-5 py-4 text-center"><span className="font-semibold text-slate-800">{displayNumber(row.quantity)}</span> <span className="text-xs text-slate-400">{row.unit}</span></td><td className="px-5 py-4 text-center text-slate-600">{displayNumber(row.minimum_quantity)}</td><td className="px-5 py-4 text-slate-600">{money(row.unit_price)}</td><td className="px-5 py-4 text-slate-600">{money(row.value)}</td><td className="px-5 py-4"><span className={`inline-flex rounded-full border px-3 py-1.5 text-xs font-medium ${row.status === "IN_STOCK" ? "border-emerald-200 bg-emerald-50 text-emerald-600" : row.status === "LOW_STOCK" ? "border-amber-200 bg-amber-50 text-amber-600" : "border-slate-200 bg-slate-50 text-slate-500"}`}>{statusLabel(row.status)}</span></td><td className="px-5 py-4"><div className="flex justify-end items-center gap-2"><Button onClick={() => { setAdjusting(row); setAdjustment(""); }} className="h-9 rounded-lg bg-slate-950 hover:bg-slate-800 gap-2 px-3"><SlidersHorizontal className="w-4 h-4" />Adjust</Button><Button variant="ghost" size="icon" className="h-9 w-9 text-slate-400 hover:text-destructive" onClick={() => void remove(Number(row.id))}><Trash2 className="w-4 h-4" /></Button></div></td></tr>)}</tbody></table></CardContent></Card>
    {adjusting && <div className="fixed inset-0 z-[100] bg-black/50 backdrop-blur-sm flex items-center justify-center p-4"><Card className="w-full max-w-md rounded-2xl"><CardContent className="p-6 space-y-5"><div className="flex items-start justify-between"><div><h3 className="text-lg font-semibold">Adjust Stock</h3><p className="text-sm text-muted-foreground mt-1">{adjusting.name} · Current: {displayNumber(adjusting.quantity)} {adjusting.unit}</p></div><Button variant="ghost" size="icon" onClick={() => setAdjusting(null)}><X className="w-4 h-4" /></Button></div><div className="space-y-2"><Label>Adjustment *</Label><Input type="number" step="1" value={adjustment} onChange={(e) => setAdjustment(e.target.value)} placeholder="e.g. 5 or -2" /><p className="text-xs text-muted-foreground">Positive adds stock, negative removes stock.</p></div><div className="flex justify-end gap-2"><Button variant="outline" onClick={() => setAdjusting(null)}>Cancel</Button><Button onClick={() => void adjust()} disabled={saving || !Number.isInteger(Number(adjustment)) || Number(adjustment) === 0}>Save Adjustment</Button></div></CardContent></Card></div>}
    {formOpen && <div className="fixed inset-0 z-[100] bg-black/50 backdrop-blur-sm flex items-center justify-center p-4"><Card className="w-full max-w-2xl max-h-[92vh] overflow-y-auto rounded-2xl"><CardContent className="p-6"><div className="flex items-start justify-between mb-6"><div><h3 className="text-lg font-semibold">{editing ? "Edit" : "Add"} Inventory Item</h3><p className="text-sm text-muted-foreground mt-1">Required fields are marked with *</p></div><Button variant="ghost" size="icon" onClick={closeForm}><X className="w-4 h-4" /></Button></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><div className="sm:col-span-2 space-y-1.5"><Label>Item Name *</Label><Input value={form.name} onChange={(e) => setForm((p) => ({ ...p, name: e.target.value }))} />{validation.name && <p className="text-xs text-destructive">{validation.name}</p>}</div><div className="space-y-1.5"><Label>Category *</Label><Input list="inventory-categories" value={form.category} onChange={(e) => setForm((p) => ({ ...p, category: e.target.value }))} /><datalist id="inventory-categories">{categories.map((c) => <option key={c} value={c} />)}</datalist>{validation.category && <p className="text-xs text-destructive">{validation.category}</p>}</div><div className="space-y-1.5"><Label>Unit *</Label><Input value={form.unit} onChange={(e) => setForm((p) => ({ ...p, unit: e.target.value }))} />{validation.unit && <p className="text-xs text-destructive">{validation.unit}</p>}</div><div className="space-y-1.5"><Label>In Stock *</Label><Input type="number" min="0" step="1" value={form.quantity} onChange={(e) => setForm((p) => ({ ...p, quantity: e.target.value }))} />{validation.quantity && <p className="text-xs text-destructive">{validation.quantity}</p>}</div><div className="space-y-1.5"><Label>Minimum Quantity *</Label><Input type="number" min="0" step="1" value={form.minimum_quantity} onChange={(e) => setForm((p) => ({ ...p, minimum_quantity: e.target.value }))} />{validation.minimum_quantity && <p className="text-xs text-destructive">{validation.minimum_quantity}</p>}</div><div className="space-y-1.5 sm:col-span-2"><Label>Unit Price *</Label><Input type="number" min="0" step="0.01" value={form.unit_price} onChange={(e) => setForm((p) => ({ ...p, unit_price: e.target.value }))} placeholder="0.00" />{validation.unit_price && <p className="text-xs text-destructive">{validation.unit_price}</p>}</div></div><div className="flex justify-end gap-2 border-t pt-5 mt-6"><Button variant="outline" onClick={closeForm}>Cancel</Button><Button onClick={() => void save()} disabled={saving || Object.keys(validation).length > 0} className="bg-orange-500 hover:bg-orange-600">{saving ? "Saving…" : "Save Item"}</Button></div></CardContent></Card></div>}
  </div>;
}
