import { useEffect, useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Edit3, Plus, Save, Trash2, X } from "lucide-react";
import { formatCurrency } from "@/lib/format";

type PackageRow = { id: number; name: string; code: string; price: number | string; description?: string | null; status: string };
type Service = { id: number; name: string; code: string; price: number | string; status: string };
type Item = { service_id: number; quantity: number; name: string; code: string; price: number | string };

async function read(response: Response) { const data = await response.json().catch(() => null); if (!response.ok) throw new Error(data?.error || `Request failed (${response.status})`); return data; }

export default function PackagesManagement() {
  const [packages, setPackages] = useState<PackageRow[]>([]); const [services, setServices] = useState<Service[]>([]); const [selected, setSelected] = useState<PackageRow | null>(null); const [items, setItems] = useState<Item[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const [name, setName] = useState(""); const [code, setCode] = useState(""); const [price, setPrice] = useState(""); const [description, setDescription] = useState(""); const [status, setStatus] = useState("ACTIVE"); const [showCreate, setShowCreate] = useState(false);
  const [editingPackage, setEditingPackage] = useState<PackageRow | null>(null);

  const load = async () => { setLoading(true); setError(""); try { const [p, s] = await Promise.all([fetch("/api/admin/packages"), fetch("/api/admin/services")]); setPackages(await read(p)); setServices(await read(s)); } catch (e) { setError(e instanceof Error ? e.message : "Failed to load packages."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const loadItems = async (pkg: PackageRow) => { setSelected(pkg); setError(""); try { const response = await fetch(`/api/admin/packages/${pkg.id}/services`); setItems(await read(response)); } catch (e) { setError(e instanceof Error ? e.message : "Failed to load package services."); setItems([]); } };
  const addService = (serviceId: number) => { if (!serviceId || items.some((item) => item.service_id === serviceId)) return; const service = services.find((s) => s.id === serviceId); if (service) setItems((current) => [...current, { service_id: service.id, quantity: 1, name: service.name, code: service.code, price: service.price }]); };
  const available = useMemo(() => services.filter((s) => s.status === "ACTIVE" && !items.some((i) => i.service_id === s.id)), [services, items]);
  const saveItems = async () => { if (!selected) return; setSaving(true); setError(""); try { await read(await fetch(`/api/admin/packages/${selected.id}/services`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ items: items.map((item) => ({ service_id: item.service_id, quantity: item.quantity })) }) })); await loadItems(selected); } catch (e) { setError(e instanceof Error ? e.message : "Failed to save package services."); } finally { setSaving(false); } };
  const createPackage = async () => { setSaving(true); setError(""); try { await read(await fetch("/api/admin/packages", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, code, price: Number(price), description, status }) })); setName(""); setCode(""); setPrice(""); setDescription(""); setShowCreate(false); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Failed to create package."); } finally { setSaving(false); } };
  const startEdit = (pkg: PackageRow) => { setEditingPackage(pkg); setName(pkg.name); setCode(pkg.code); setPrice(String(pkg.price)); setDescription(pkg.description ?? ""); setStatus(pkg.status || "ACTIVE"); setError(""); };
  const cancelEdit = () => { setEditingPackage(null); setName(""); setCode(""); setPrice(""); setDescription(""); setStatus("ACTIVE"); };
  const updatePackage = async () => { if (!editingPackage) return; setSaving(true); setError(""); try { const updated = await read(await fetch(`/api/admin/packages/${editingPackage.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, code, price: Number(price), description, status }) })); setPackages((current) => current.map((pkg) => pkg.id === updated.id ? updated : pkg)); if (selected?.id === updated.id) setSelected(updated); cancelEdit(); } catch (e) { setError(e instanceof Error ? e.message : "Failed to update package."); } finally { setSaving(false); } };
  const deletePackage = async (pkg: PackageRow) => { if (!window.confirm(`Delete package "${pkg.name}"? This will also remove its service assignments.`)) return; setSaving(true); setError(""); try { await read(await fetch(`/api/admin/packages/${pkg.id}`, { method: "DELETE" })); setPackages((current) => current.filter((item) => item.id !== pkg.id)); if (selected?.id === pkg.id) { setSelected(null); setItems([]); } if (editingPackage?.id === pkg.id) cancelEdit(); } catch (e) { setError(e instanceof Error ? e.message : "Failed to delete package."); } finally { setSaving(false); } };

  return <div className="p-8 max-w-7xl mx-auto w-full space-y-6">
    <div className="flex items-center justify-between"><div><h2 className="text-2xl font-bold">Packages</h2><p className="text-muted-foreground">Configure package details, pricing and the services included in each package.</p></div><Button onClick={() => setShowCreate(true)}><Plus className="w-4 h-4 mr-2" />New Package</Button></div>
    {error && <div className="rounded-lg border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive">{error}</div>}
    {showCreate && <Card><CardHeader><CardTitle>New Package</CardTitle></CardHeader><CardContent className="grid grid-cols-2 gap-4"><div><Label>Name</Label><Input value={name} onChange={(e) => setName(e.target.value)} /></div><div><Label>Code</Label><Input value={code} onChange={(e) => setCode(e.target.value)} /></div><div><Label>Price</Label><Input type="number" min="0" value={price} onChange={(e) => setPrice(e.target.value)} /></div><div><Label>Status</Label><select className="w-full h-10 rounded-md border bg-background px-3" value={status} onChange={(e) => setStatus(e.target.value)}><option value="ACTIVE">Active</option><option value="INACTIVE">Not Active</option></select></div><div className="col-span-2"><Label>Description</Label><Input value={description} onChange={(e) => setDescription(e.target.value)} /></div><div className="col-span-2 flex justify-end gap-2"><Button variant="outline" onClick={() => setShowCreate(false)}><X className="w-4 h-4 mr-2" />Cancel</Button><Button onClick={createPackage} disabled={saving || !name || !code || price === ""}><Save className="w-4 h-4 mr-2" />Create</Button></div></CardContent></Card>}
    {editingPackage && <Card><CardHeader><CardTitle>Edit Package</CardTitle></CardHeader><CardContent className="grid grid-cols-2 gap-4"><div><Label>Name</Label><Input value={name} onChange={(e) => setName(e.target.value)} /></div><div><Label>Code</Label><Input value={code} onChange={(e) => setCode(e.target.value)} /></div><div><Label>Price</Label><Input type="number" min="0" value={price} onChange={(e) => setPrice(e.target.value)} /></div><div><Label>Status</Label><select className="w-full h-10 rounded-md border bg-background px-3" value={status} onChange={(e) => setStatus(e.target.value)}><option value="ACTIVE">Active</option><option value="INACTIVE">Not Active</option></select></div><div className="col-span-2"><Label>Description</Label><textarea className="min-h-24 w-full rounded-md border bg-background px-3 py-2 text-sm" value={description} onChange={(e) => setDescription(e.target.value)} /></div><div className="col-span-2 flex justify-end gap-2"><Button variant="outline" onClick={cancelEdit} disabled={saving}><X className="w-4 h-4 mr-2" />Cancel</Button><Button onClick={updatePackage} disabled={saving || !name || !code || price === ""}><Save className="w-4 h-4 mr-2" />{saving ? "Saving..." : "Save Changes"}</Button></div></CardContent></Card>}
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-6"><Card><CardHeader><CardTitle>Packages</CardTitle></CardHeader><CardContent className="space-y-3">{loading ? <p className="text-muted-foreground">Loading...</p> : packages.map((pkg) => <div key={pkg.id} onClick={() => void loadItems(pkg)} role="button" tabIndex={0} onKeyDown={(e) => { if (e.key === "Enter" || e.key === " ") void loadItems(pkg); }} className={`w-full text-left rounded-lg border p-4 transition cursor-pointer ${selected?.id === pkg.id ? "border-primary bg-primary/5" : "hover:border-primary/40"}`}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="font-medium truncate">{pkg.name}</div><div className="text-xs text-muted-foreground font-mono">{pkg.code}</div>{pkg.description && <div className="text-sm text-muted-foreground mt-1 line-clamp-2">{pkg.description}</div>}</div><div className="text-right shrink-0"><div className="font-mono">{formatCurrency(Number(pkg.price))}</div><div className="text-xs text-muted-foreground mt-1">{pkg.status === "ACTIVE" ? "Active" : "Not Active"}</div></div></div><div className="flex justify-end gap-2 mt-3 pt-3 border-t"><Button variant="outline" size="sm" onClick={(e) => { e.stopPropagation(); startEdit(pkg); }}><Edit3 className="w-4 h-4 mr-2" />Edit</Button><Button variant="destructive" size="sm" disabled={saving} onClick={(e) => { e.stopPropagation(); void deletePackage(pkg); }}><Trash2 className="w-4 h-4 mr-2" />Delete</Button></div></div>)}{!loading && packages.length === 0 && <p className="text-muted-foreground">No packages yet.</p>}</CardContent></Card>
    <Card><CardHeader><CardTitle>{selected ? `Services in ${selected.name}` : "Package Services"}</CardTitle></CardHeader><CardContent className="space-y-4">{!selected ? <p className="text-muted-foreground">Select a package to configure its services.</p> : <><div className="flex gap-2"><select className="flex-1 h-10 rounded-md border bg-background px-3" defaultValue="" onChange={(e) => { addService(Number(e.target.value)); e.currentTarget.value = ""; }}><option value="">Add a service...</option>{available.map((s) => <option key={s.id} value={s.id}>{s.name} • {formatCurrency(Number(s.price))}</option>)}</select></div>{items.map((item, index) => <div key={item.service_id} className="flex items-center gap-3 rounded-lg border p-3"><div className="flex-1"><div className="font-medium">{item.name}</div><div className="text-xs text-muted-foreground font-mono">{item.code}</div></div><Input className="w-24" type="number" min="1" value={item.quantity} onChange={(e) => setItems((current) => current.map((x, i) => i === index ? { ...x, quantity: Math.max(1, Number(e.target.value) || 1) } : x))} /><Button variant="ghost" size="icon" onClick={() => setItems((current) => current.filter((x) => x.service_id !== item.service_id))}><Trash2 className="w-4 h-4" /></Button></div>)}<Button onClick={saveItems} disabled={saving}><Save className="w-4 h-4 mr-2" />{saving ? "Saving..." : "Save Package Services"}</Button></>}</CardContent></Card></div>
  </div>;
}
