// Catch-all Vercel entrypoint for the Express API.
// The API server is bundled before Vercel processes this function.
// @ts-ignore - dist/index.mjs is generated by the Vercel build command.
export { default } from "../artifacts/api-server/dist/index.mjs";
