// The API server is bundled with esbuild during the Vercel build.
// Keeping the Vercel function entrypoint pointed at the bundled output
// prevents Vercel's TypeScript checker from traversing the server workspace.
// @ts-ignore - the bundled .cjs file is generated by the build command.
export { default } from "../artifacts/api-server/dist/index.cjs";
