// Explicit Vercel function for the analytics range endpoint.
// This avoids relying on the root catch-all function for the nested analytics route.
// @ts-ignore - dist/index.cjs is generated by the Vercel build command.
export { default } from "../../artifacts/api-server/dist/index.cjs";
